# 1) WWW -> sem WWW (SEM ir pro app)
server {
    listen 80;
    server_name www.zapschat.com.br;

    return 301 https://zapschat.com.br$request_uri;
}

# 2) Domínio principal -> proxy pro app
upstream zapchats_upstream {
    server zapschat_app-zapchats:8000;
    keepalive 32;
}

server {
    listen 80;
    server_name zapschat.com.br;

    proxy_intercept_errors on;
    error_page 502 503 504 = /maintenance.html;

    location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
    }

    location = /__alive {
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location /ws {
        proxy_pass http://zapchats_upstream;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
    }

    location / {
        proxy_pass http://zapchats_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}